config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows do
    member do
      get :remove_favourite
      get :add_favourite
    end
  end
  devise_for :users

  root to: "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :tv_shows
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :tv_show
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  belongs_to :channel
  has_many :viewers, class_name: 'Favourite', foreign_key: 'user_id'
  has_many :users, through: :viewers

  scope :upcoming, -> (time) { where(telecast_time: Time.now..(Time.now + time )) }

  def notify_viewer
    users.each do |user|
      NotificationMailer.notify_viewer(user.id, id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites, dependent: :destroy
  has_many :tv_shows, through: :favourites

  def favourite_show?(tv_show)
    tv_shows.include?(tv_show)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @tv_shows = TvShow.all
    @favourite_shows = current_user.tv_shows
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController

  before_action :get_show

  def remove_favourite
    current_user.favourites.find_by(tv_show_id: @show.id)&.delete
    redirect_to root_path
  end

  def add_favourite
    current_user.favourites.create(tv_show_id: @show.id)
    redirect_to root_path
  end

  private
    def get_show
      @show ||= TvShow.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <table id="show-list" class="table table-striped table-bordered">
        <thead>
          <th> Channel </th>
          <th> Tv Show</th>
          <th> Telecast Time</th>
          <th> Favourite </th>
        </thead>
        <tbody>
            <%= render partial: "shared/tv_show", collection: @tv_shows, as: :tv_show %>
        </tbody>
      </table>
    </div>
    <div class="col-4">
      <h4> Favourite Tv Shows </h4>
      <%= render partial: "shared/tv_show", collection: @favourite_shows, as: :tv_show %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvAlert</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render partial: "shared/nav_bar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path) %>  
  </li>
<% end %>

app/views/shared/_tv_show.html.erb
<tr>
	<td><%= tv_show.channel.name %></td>
	<td><%= tv_show.name %></td>
	<td><%= tv_show.telecast_time %></td>
	<td>
		<% if current_user.favourite_show?(tv_show) %>
			<%= link_to "Remove favourite", remove_favourite_tv_show_path(tv_show) %>
		<% else %>
			<%= link_to "Mark favourite", add_favourite_tv_show_path(tv_show) %>
		<% end %>
	</td>
</tr>